### ISSUE TITLE
[feat/configuration-v2] Configuration Revamp Milestones

### ISSUE THREAD

**Issue by lennoxlotl** [officialLennox/rainbowify#7]
### **Major Changes**

- [x] Support sliders
- [x] Category support (be able to sort stuff easily)
- [x] Get rid of static abuse

### **Minor Changes**

- [x] Change the configuration file loading and saving (it is currently pretty messy, could be done better)
- [x] Properly use the new Minecraft option system (even tho it is pretty annoying, better than broken implementation)
- [x] Maybe improve code otherwise if possible

These are all changes needed to be done for this to be pushed to master (1.19)

**Comment by lennoxlotl** [comment]
merged into master
